#!/bin/bash

# Author: Robert H Cudmore
# Date: 20190401
#
# Purpose: Bash script to install bAnalysisApp
#	1) create a python3 virtual environment in bAnalysis_env/
#	2) install requirements.txt
#
# Usage:
#	./install

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

if ! type "virtualenv" > /dev/null; then
	echo '==='
	echo "=== install bAnalysisApp: Installing virtualenv"
	echo '==='
	#sudo /usr/bin/easy_install virtualenv
	pip install virtualenv
	# debian
	#sudo apt-get -qy install python-virtualenv
fi

if [ ! -d "bAnalysis_env/" ]; then
	echo '==='
	echo "=== install bAnalysisApp: Making Python 3 virtual environment in $PWD/bAnalysis_env"
	echo '==='
	if ! type "virtualenv" > /dev/null; then
		echo -e 'install bAnalysisApp: ${RED}ERROR${NC}: DID NOT INSTALL VIRTUALENV -->> ABORTING'
		exit 0
	else
		mkdir bAnalysis_env
		virtualenv -p python3 --no-site-packages bAnalysis_env
	fi
else
	echo '==='
	echo "=== install bAnalysisApp: Python 3 virtual environment already exists in $PWD/bAnalysis_env"
	echo '==='
fi



if [ -f "bAnalysis_env/bin/activate" ]; then
	echo '==='
	echo "=== install bAnalysisApp: Activating Python 3 virtual environment with 'source bAnalysis_env/bin/activate'"
	echo '==='
	source bAnalysis_env/bin/activate
else
	echo -e "${RED}ERROR${NC}: Python 3 virtual environment did not install in $PWD/bAnalysis_env"
	echo "Make sure virtualenv is installed and try installing again"
	exit 1
fi


echo '==='
echo "=== install bAnalysisApp: Installing required python libraries with 'pip install -r requirements.txt'"
echo '==='
pip install -r requirements.txt

deactivate

echo -e "${GREEN}Install successful${NC}. Run the Analysis app with './run'"
