#!/bin/bash

# Author: Robert H Cudmore
# Date: 20190718
#
# Purpose: Bash script to run SanPy
#	1) Make sure virtual environment exists in sanpy_env/
#	2) activate sanpy_env
#   3) run 'python sanpy_app.py'
#
# Usage:
#	./run

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
echo -e "Running run from $DIR"
cd "${DIR}"

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

if [ ! -d "sanpy_env/" ]; then
	echo '==='
	echo -e "=== ${RED}warning${NC}: virtual environment does not exist in $PWD/sanpy_env"
	echo "=== installing with './install'"
	./install
  	#echo '==='
	#exit 1
fi

if [ -f "sanpy_env/bin/activate" ]; then
	echo '==='
	echo "=== run SanPy: Activating Python 3 virtual environment with 'source sanpy_env/bin/activate'"
	source sanpy_env/bin/activate
fi

echo "=== run SanPy: running 'python sanpy/sanpy_app.py'"
echo "=== run sanpy_app: interface should appear shortly ... "
echo '==='
#python sanpy/interface/sanpy_app.py
sanpy

$SHELL
