#!/bin/bash

# Author: Robert H Cudmore
# Date: 20190718
#
# Purpose: Bash script to install SanPy
#	1) create a python3 virtual environment in sanpy_env/
#	2) install requirements.txt
#
# Usage:
#	./install

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

if ! type "virtualenv" > /dev/null; then
	echo '==='
	echo "=== install SanPy: Installing virtualenv with pip"
	echo '==='
	#sudo /usr/bin/easy_install virtualenv
	pip install virtualenv
	# debian
	#sudo apt-get -qy install python-virtualenv
fi

if [ ! -d "sanpy_env/" ]; then
	echo '==='
	echo "=== install SanPy: Making Python 3 virtual environment in $PWD/sanpy_env"
	echo '==='
	if ! type "virtualenv" > /dev/null; then
		echo -e 'install SanPy: ${RED}ERROR${NC}: DID NOT INSTALL VIRTUALENV -->> ABORTING'
		exit 0
	else
		mkdir sanpy_env
		#virtualenv -p python3 --no-site-packages sanpy_env
		python3 -m venv sanpy_env
	fi
else
	echo '==='
	echo "=== install SanPy: Python 3 virtual environment already exists in $PWD/sanpy_env"
	echo '==='
fi



if [ -f "sanpy_env/bin/activate" ]; then
	echo '==='
	echo "=== install SanPy: Activating Python 3 virtual environment with 'source sanpy_env/bin/activate'"
	echo '==='
	source sanpy_env/bin/activate
else
	echo -e "${RED}ERROR${NC}: Python 3 virtual environment did not install in $PWD/sanpy_env"
	echo "Make sure Python package virtualenv is installed and try installing again"
	exit 1
fi


echo '==='
echo "=== install SanPy: Installing required python libraries with 'pip install -r requirements.txt'"
echo '==='
pip install -r requirements.txt

deactivate

echo -e "${GREEN}Install successful${NC}. Run the Analysis app with './run'"
