import dash
import dash_bootstrap_components as dbc

myStyles = 'assets/myStyle.css'
# bootstrap theme
# https://bootswatch.com/lux/
external_stylesheets = [dbc.themes.DARKLY, myStyles]

app = dash.Dash(__name__, external_stylesheets=external_stylesheets)

server = app.server
app.config.suppress_callback_exceptions = True

'''
If you are assigning callbacks to components that are
generated by other callbacks (and therefore not in the
initial layout), you can suppress this exception by setting
suppress_callback_exceptions
'''
