name: Coverage
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - '**'

jobs:

  build-and-test:
    name: coverage
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
      - uses: actions/checkout@v3

      - name: Configure Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
          architecture: x64

      - name: Install dependencies
        run: |
          #sudo ./.github/workflows/install-ubuntu-dependencies.sh

      - name: Install Myokit
        run: |
          python --version
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install .[gui]
          python -m pip install coverage codecov

      - name: Run coverage tests
        run: |
          sanpy
          coverage run sanpy

      - name: Submit report to codecov
        if: success()
        run: |
          codecov
