# my twine key is in
#         TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}

name: Publish sanpy-ephys to PyPi (cudmore)

on:
  workflow_run:
    workflows: ["Release (cudmore)"]
    types: [completed]
    #branches: [master]

jobs:
  deploy:
    # this will run when you have tagged a commit, starting with "v*"
    # and requires that you have put your twine API key in your
    # github secrets (see readme for details)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source (cudmore)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # needed so setuptools_scm can get tags
      - name: Set up Python (cudmore)
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install dependencies (cudmore)
        run: |
          python -m pip install --upgrade pip
          pip install -U setuptools wheel twine build
          pip install -U '.[gui]'
      - name: Build and publish (cudmore)
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          git tag
          #python setup.py --version
          python -m build .
          twine upload dist/*