# create a release when we get a push with a v* tag
# see tutorial: https://github.com/marketplace/actions/create-release

name: Release (cudmore)

on: 
  push:
    tags:
    - 'v*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "data/2021_07_20_0010.csv"
        bodyFile: "CHANGELOG.md"